title: Hello there
author: Kope
email: m@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning
theme: minima
# social links
twitter_username: optn1
github_username: optn1

show_excerpts: true # set to false to remove excerpts on the homepage
